version: '3.9'

services:

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: api
    image: ufo/api:latest
    env_file:
      - conf/ufo.env
    ports:
      - 8001:8001
    volumes:
      - ./conf/supervisord-agent.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./logs:/opt/ufo/logs
      - ./logs/cron.log:/var/log/cron.log

  scrape:
    build:
      context: .
      dockerfile: docker/Dockerfile.scrape
    container_name: scrape
    image: ufo/scrape:latest
    env_file:
      - conf/ufo.env
    depends_on:
      - mongodb
    links:
      - mongodb

  mongodb:
      image: mongo:latest
      container_name: mongodb
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: rootpassword
      ports:
        - 27017:27017
      volumes:
        - mongodb_data_container:/data/db

  nginx:
    image: ufo/nginx:latest
    container_name: nginx
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/mime.types:/etc/nginx/conf/mime.types
      - ./logs:/etc/nginx/logs
    depends_on:
      - api
    links:
      - api
    ports:
      - 80:80
      - 443:443

volumes:
  mongodb_data_container:
