version: '3.9'

services:

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: api
    image: ufo/api:local
    environment:
      - "UFO_DATA_URL=http://......"
    ports:
      - 8000:8003
    profiles:
      - api
    volumes:
      - ./conf/supervisord-agent.conf:/etc/supervisor/conf.d/supervisord.conf

  mongodb:
      image: mongo:latest
      container_name: mongodb
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: rootpassword
      ports:
        - 27017:27017
      volumes:
        - mongodb_data_container:/data/db

  nginx:
    image: ufo/nginx:local
    container_name: nginx
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/mime.types:/etc/nginx/conf/mime.types
      - ./logs:/etc/nginx/logs
    depends_on:
      - api
    links:
      - api
    ports:
      - 80:80
      - 443:443

volumes:
  mongodb_data_container:
