FROM nginx:alpine

ADD ./conf/nginx.conf /etc/nginx/nginx.conf
ADD ./conf/mime.types /etc/nginx/conf/mime.types
ADD ./static /var/share/html/swaggerui
ADD ./static/swagger.json /var/share/html/swagger.json
ADD ./certs /etc/nginx/certs
